### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by TrurlMcByte** [hylozero/redmine_tpa#1]
## Error

RAILS_ENV=production rake db:migrate_plugins NAME=redmine_tpa --trace

```
rake aborted!
rake aborted!
ArgumentError: invalid byte sequence in US-ASCII
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:16:in `block in trace_on'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `map'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/trace_output.rb:14:in `trace_on'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:376:in `trace'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:222:in `display_exception_message_details'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:209:in `display_exception_details'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:198:in `display_error_message'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/lib64/ruby/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'
```
## Info

```
Environment:
  Redmine version                3.0.4.stable
  Ruby version                   1.9.3-p392 (2013-02-22) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.7.7
  Cvs                            1.12.12
  Git                            1.7.10.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.4
  advanced_roadmap_v2            2.4.2
  global_roles                   2.0.0
  redmine_dmsf                   1.5.2
  redmine_issue_tabs             1.1.0
  redmine_lightbox2              0.2.2
  redmine_revision_branches      0.3.0
  redmine_tpa                    0.0.1
  unread_issues                  1.5.0
  usability                      1.3.0
```

**Comment by aceccarelli** [comment]
Olá Renato!
Estou com o mesmo problema que @TrurlMcByte relatou.
Poderia ajudar-me?
Valeu!
